# Generated by Django 2.1.5 on 2019-03-21 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myBlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('host', models.URLField(primary_key=True, serialize=False)),
                ('shareImages', models.BooleanField(default=True)),
                ('sharePost', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=400)),
                ('password', models.CharField(max_length=400)),
                ('nodeUser', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
