# Generated by Django 2.1.5 on 2019-02-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='open_to',
            field=models.CharField(choices=[('me', 'me'), ('author', 'author'), ('friends', 'friends'), ('FoF', 'FoF'), ('public', 'public')], default='me', max_length=32),
            preserve_default=False,
        ),
    ]
