# Generated by Django 2.1.5 on 2019-02-21 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0002_auto_20190221_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='postid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
