# Generated by Django 2.1.5 on 2019-02-21 06:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0003_auto_20190220_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(editable=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
