# Generated by Django 2.1.5 on 2019-02-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0003_auto_20190221_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
