# Generated by Django 2.1.5 on 2019-03-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0003_auto_20190321_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='password',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='username',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
