# Generated by Django 2.1.5 on 2019-03-22 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0004_auto_20190321_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='nodeUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
