# Generated by Django 2.1.5 on 2019-02-21 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0004_auto_20190221_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='sender', serialize=False, to='myBlog.Author')),
                ('status', models.CharField(choices=[('Accept', 'Accept'), ('Decline', 'Decline'), ('Pending', 'Pending')], default='Pending', max_length=32)),
                ('last_modified_time', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reciver', to='myBlog.Author')),
            ],
        ),
    ]
